<?php namespace JF;
/**

Copyright 2018 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-ec8e1e
Date:    2018-03-12 13:53:33
Version: v2.1.0
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-ec8e1e",
    "email": {
        "to": "dlewandowski38@yahoo.com",
        "cc": "",
        "bcc": "",
        "subject": "PAUL RAND WEBSITE CONTACT",
        "template": "You receive an email from {sender.f1}.\n\nThe web form data:\n{dataTable}\n\nReference ID: {AutoID}\nIP: {IP}\nDate: {Date}\nTime: {Time}\nWebsite: {HTTP_HOST}\nReferer: {HTTP_REFERER}\n",
        "fromName": "{f2}"
    },
    "admin": {
        "users": "admin:4]9URGFW8ywEZk@M8pu3$Z9nGWs29C(G(rbMJYgma$eDtCC9JiR].\/jFtz$Fqa2L",
        "dataDelivery": "emailAndFile",
        "save2dbExample": false
    },
    "thankyou": {
        "url": "thanks.h",
        "message": "Your message has been sent. I'll get back to you shortly. \n\nThank You!\nDanny Lewandowski",
        "seconds": "10"
    },
    "autoResponse": {
        "includeAttachments": false,
        "subject": "Paul Rand: Thank you for your message",
        "template": "Thanks for your message! I'll reply soon.\n\nAll the best,\nDanny Lewandowski\n\nwww.paulrand.design"
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "local",
    "smtp": {
        "host": "",
        "user": "",
        "password": ""
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "black"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [

    ],
    "fields": [
        {
            "label": "Name",
            "field_type": "name",
            "field_options": {
                "size": "small",
                "sender": "fullname",
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Sorry, but need to know your name so I can reply. They call you\u2026"
                    }
                },
                "placeholder": "Who are you?",
                "addon": {
                    "leftIcon": ""
                }
            },
            "id": "f1",
            "cid": "c1"
        },
        {
            "label": "Email",
            "field_type": "email",
            "field_options": {
                "size": "small",
                "sender": true,
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true,
                        "msg": "Sorry, but need your email so I can reply. Fill it in here, please."
                    }
                },
                "addon": {
                    "leftIcon": "",
                    "leftText": ""
                },
                "placeholder": "Where are you?"
            },
            "id": "f2",
            "cid": "c2"
        },
        {
            "label": "Subject",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Why are you writing?",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Just saying \u201cHi\u201d",
                        "checked": false,
                        "value": "Just saying \u201cHi\u201d"
                    },
                    {
                        "label": "Problem with the site (technical or something not working properly)",
                        "checked": false,
                        "value": "Problem with the site (technical or something not working properly)"
                    },
                    {
                        "label": "Problem with the content (words or images)",
                        "checked": false,
                        "value": "Problem with the content (words or images)"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": true,
                        "msg": "Why are you writing? Please select\u2026"
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "id": "f4",
            "cid": "c28"
        },
        {
            "label": "Message",
            "field_type": "paragraph",
            "field_options": {
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "No blank messages, please. How can I help?"
                    }
                },
                "addon": {
                    "leftIcon": "glyphicon glyphicon-edit"
                },
                "placeholder": "What's up?"
            },
            "id": "f3",
            "cid": "c3"
        },
        {
            "label": "Share a file (optional, but certainly appreciated)\u2026",
            "field_type": "file",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "file": {
                    "showPreview": true,
                    "showRemove": true,
                    "browseLabel": ""
                },
                "multiple": true
            },
            "id": "f5",
            "cid": "c35"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ],
    "licenseKey": ""
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class